package com.example.holyclick;

public enum ErrorResponseCode {
    USER_PASSWORD_NOT_VALID,
    USER_PASSWORDS_DO_NOT_MATCH,
    USER_ALREADY_EXIST,
    USER_WRONG_USERNAME,
    USER_WRONG_PASSWORD,
    USER_NOT_FOUND,
    PERSONA_ALREADY_EXISTS,
    INVALID_ADMIN_KEY,
    PERSONA_NOT_FOUND,
    PERSONA_NOT_BELONG_TO_USER,
    INVALID_PERSONA_TYPE
}
